pipeline:
  build_docker_image:
    image: docker:18.09
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t sonar-scanner:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  scan_image:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: sonar-scanner
    when:
      event: push

  image_sha_to_quay:
    image: docker:18.09
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag sonar-scanner:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/sonar-scanner:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/sonar-scanner:$${DRONE_COMMIT_SHA}
    when:
      event: push

  image_latest_to_quay:
    image: docker:18.09
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag sonar-scanner:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/sonar-scanner:latest
      - docker push quay.io/ukhomeofficedigital/sonar-scanner:latest
    when:
      branch: master
      event: push

  image_tag_to_quay:
    image: docker:18.09
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag sonar-scanner:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/sonar-scanner:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/sonar-scanner:$${DRONE_TAG}
    when:
      event: tag
