---
kind: pipeline
name: default
type: kubernetes

trigger:
  event:
    exclude:
    - pull_request

platform:
  os: linux
  arch: amd64

steps:
- name: build_docker_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - /usr/local/bin/wait
  - docker build -t sonar-scanner:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push
    - tag

- name: scan_image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  pull: always
  environment:
    IMAGE_NAME: sonar-scanner:${DRONE_COMMIT_SHA}
    LOCAL_IMAGE: true
    ALLOW_CVE_LIST_FILE: whitelist
    SEVERITY: HIGH,CRITICAL
  when:
    event:
    - push
    - tag
  depends_on:
    - build_docker_image

- name: image_sha_to_quay
  pull: if-not-exists
  image: plugins/docker
  settings: 
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonar-scanner
    tags: ${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_SECRET_2
    DOCKER_USERNAME: ukhomeofficedigital+sonar_scanner
  when:
    event:
    - push
  depends_on:
    - scan_image

- name: image_tag_to_quay
  pull: if-not-exists
  image: plugins/docker
  settings: 
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonar-scanner
    tags: ${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_SECRET_2
    DOCKER_USERNAME: ukhomeofficedigital+sonar_scanner
  when:
    event:
    - tag
  depends_on:
    - scan_image

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
